# Generated by Django 4.0.3 on 2022-03-27 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='time',
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='due_at',
            field=models.DateTimeField(null=True),
        ),
    ]
