# Generated by Django 4.0.3 on 2022-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_card_date_remove_card_time_card_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
